package com.example.tvapp;

import java.util.HashMap;

import android.app.Activity;

public class Base extends Activity {
	public String baseURL = "http://api-tv-program.herokuapp.com/";
	
	
	public static final HashMap<String, String> channelName = new HashMap<String, String>(){{
		put("MDO","A&E Mundo");
		put("APL","Animal Planet");
		put("NEW","Band News");
		put("BSP","Band Sports");
		put("BAN","Bandeirantes");
		put("BPO","Bandeirantes Sao Paulo");
		put("BBC","BBC World");
		put("BEM","Bem Simples");
		put("BIT","Bloomberg");
		put("BMG","Boomerang");
		put("CBR","Canal Brasil");
		put("FUT","Canal Futura");
		put("RUR","Canal Rural");
		put("CNV","Canção Nova");
		put("CAR","Cartoon Network");
		put("MNX","Cinemax");
		put("CLI","Clima Tempo");
		put("CNE","CNN Espanhol");
		put("CNN","CNN International");
		put("CNT","CNT");
		put("CCE","Comedy Central");
		put("DWL","Deutsche Welle");
		put("DIS","Discovery Channel");
		put("DHD","Discovery HD Theater");
		put("HEA","Discovery Home & Health");
		put("DIK","Discovery Kids");
		put("TRV","Discovery Travel & Living");
		put("DTU","Discovery Turbo");
		put("DNY","Disney Channel");
		put("DNH","Disney HD");
		put("PHD","Disney Jr.");
		put("EET","E! Entertainment");
		put("ESB","ESPN Brasil");
		put("ESP","ESPN International");
		put("SPI","Esporte Interativo");
		put("EUR","EuroChannel");
		put("FAS","Fashion TV");
		put("BRA","FEA - Film & Arts");
		put("GLS","For Man");
		put("FOX","Fox");
		put("FHD","Fox + NatGeo HD");
		put("FLI","Fox Life");
		put("FNE","Fox News");
		put("FSP","Fox Sports");
		put("CFX","FX");
		put("FAS","Glitz");
		put("GLN","Globo News");
		put("GHD","Globosat HD");
		put("GNT","GNT");
		put("HAL","Hallmark");
		put("HBO","HBO");
		put("HBE","HBO e");
		put("HFA","HBO Family");
		put("HBH","HBO HD");
		put("HPL","HBO Plus");
		put("HPE","HBO Plus e");
		put("HFE","HBO Signature");
		put("HB2","HBO 2");
		put("LIV","Investigação Discovery");
		put("SAT","i-SAT");
		put("MNG","Management TV");
		put("KID","Jetix");
		put("MXE","Max");
		put("MAX","Max HD");
		put("MAP","Max Prime");
		put("MPE","Max Prime e");
		put("MPX","Megapix");
		put("MGM","MGM");
		put("MTV","MTV Brasil");
		put("MTH","MTV Hits");
		put("MSW","Multishow");
		put("MSH","Multishow HD");
		put("NGH","Nat Geo Wild HD");
		put("SUP","National Geographic");
		put("NBR","NBR");
		put("NHK","NHK");
		put("NJR","Nick Jr");
		put("NIC","Nickelodeon");
		put("OFF","Off");
		put("TRA","People+Arts");
		put("PLA","Playboy TV");
		put("135","Premiere Combate");
		put("121","PR3 Premiere Futebol Clube");
		put("RAI","RAI (italiano)");
		put("POA","RBS TV");
		put("REC","Record");
		put("RCN","Record News");
		put("RTV","Rede TV");
		put("VDA","Rede Vida");
		put("SCC","SBT");
		put("NAC","Sesc TV");
		put("HOT","Sexy Hot");
		put("SHO","Shoptime");
		put("SIC","SIC Internacional");
		put("SET","Sony Entertainment Television");
		put("ANX","Sony Spin");
		put("SPA","Space");
		put("SPH","Space HD");
		put("SPE","Speed Channel");
		put("SPO","SPORTV");
		put("SP2","SPORTV 2");
		put("SP3","SPORTV 3");
		put("SCI","SyFy");
		put("TBS","TBS muitodivertido");
		put("TCM","TCM");
		put("TCH","Telecine HD");
		put("TC2","Telecine Action");
		put("T2H","Telecine Action HD");
		put("TC5","Telecine Cult");
		put("TC6","Telecine Fun");
		put("TC3","Telecine Light");
		put("TC4","Telecine Pipoca");
		put("T4H","Telecine Pipoca HD");
		put("TC1","Telecine Premium");
		put("TC3","Telecine Touch");
		put("TVV","Terra Viva");
		put("TGC","The Golf Channel");
		put("HIS","The History Channel");
		put("TRV","TLC");
		put("TLH","TLC HD");
		put("TNT","TNT");
		put("TNH","TNT HD");
		put("TOC","Tooncast");
		put("TRU","TruTV");
		put("TCM","Turner Classic Movies");
		put("TED","TV Brasil");
		put("CAM","TV Câmara");
		put("CNV","TV Canção Nova");
		put("CUL","TV Cultura");
		put("ESC","TV Escola");
		put("JUS","TV Justiça");
		put("RTB","TV Rá Tim Bum");
		put("SEN","TV Senado");
		put("TV5","TV5Monde");
		put("TVV","TV Terra Viva");
		put("TED","TVE Brasil");
		put("TVE","TVE Internacional");
		put("TV5","TV5MONDE");
		put("USA","Universal Channel");
		put("VH1","VH1");
		put("VHD","VH1 HD");
		put("VHS","VH1 Mega Hits");
		put("VIV","Viva");
		put("WBT","Warner");
		put("WOO","WooHoo");
	}};
}